spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviex
    username: postgres
    password: docker
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true